// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }







import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Town Club Edathua | Official Website",
  description:
    "Town Club Edathua is a premier sports club dedicated to football, cricket, volleyball and community sports development.",
  keywords: ["Town Club", "Edathua", "Sports Club", "Football", "Cricket"],
  authors: [{ name: "Town Club Edathua" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
 
    <html lang="en" className="scroll-smooth">
  <body
    className={`
      ${geistSans.variable}
      ${geistMono.variable}
      antialiased
      bg-slate-950
      text-white
      flex
      flex-col
      min-h-screen
    `}
  >
    <Navbar />

    {/* Main grows to push footer down */}
    <main className="flex-1 pt-24  bg-gradient-to-r from-indigo-900/90 via-slate-900/80 to-violet-900/90">
      {children}
    </main>

    <Footer />
  </body>
</html>
  );
}